title: "Math Notes"
markdown: kramdown

kramdown:
  input: GFM                # GitHub-style Markdown
  math_engine: mathjax      # use MathJax
  math_engine_opts:
    preview: true           # preview math

exclude:
  - .bundle
  - vendor
  - node_modules
  - .github
  - .devcontainer
  - Gemfile
  - Gemfile.lock

baseurl: "/MathNotes"

collections:
  Notes:
    output: true
