title: "Math Notes"
markdown: kramdown
theme: minima

kramdown:
  input: GFM                # GitHub-style Markdown
  math_engine: mathjax      # use MathJax
  math_engine_opts:
    preview: true           # preview math